nginx:
  # Note : Only nginx:alpine supports bcrypt.
  # If you don't need to use bcrypt, you can use a different tag.
  # Ref. https://github.com/nginxinc/docker-nginx/issues/29
  image: "nginx:alpine"
  ports:
    - 5043:443
  links:
    - registry:registry
  volumes:
    - ./auth:/etc/nginx/conf.d
    - ./auth/nginx.conf:/etc/nginx/nginx.conf:ro

registry:
  image: registry:2
  ports:
    - 127.0.0.1:5000:5000
  volumes:
    - ./data:/var/lib/registry

front-end:
  image: "konradkleine/docker-registry-frontend:2"
  ports:
    - 9080:80
  links:
    - registry:registry
  environment:
    ENV_DOCKER_REGISTRY_HOST: private.registry.local
    ENV_DOCKER_REGISTRY_PORT: 5043
    ENV_DOCKER_REGISTRY_USE_SSL: 1
